/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Zeyckler
 */
@ManagedBean
@SessionScoped
public class PaisesBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private String espana = "España";
    private String paises[] = {"España",
        "Afganistán",
        "Islas Aland ",
        "Albania",
        "Argelia",
        "Samoa Americana",
        "Andorra",
        "Angola",
        "Anguila",
        "Antártida",
        "Antigua y Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaiyán",
        "Bahamas",
        "Bahréin",
        "Bangladesh",
        "Barbados",
        "Bielorusia",
        "Bélgica",
        "Belice",
        "Benin",
        "Bermuda",
        "Bután",
        "Bolivia",
        "Bosnia y Herzegovina",
        "Botswana",
        "Isla Bouvet",
        "Brasil",
        "Territorio Británico en el Océano Indico",
        "Islas Vírgenes (Reino Unido)",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Camboya",
        "Camerún",
        "Canadá",
        "Cabo Verde",
        "Islas Caimán",
        "República Centroafricana",
        "Chad",
        "Chile",
        "China",
        "Isla de Navidad",
        "Islas Cocos (Keeling)",
        "Colombia",
        "Comores",
        "Congo",
        "Islas Cook",
        "Costa Rica",
        "Croacia",
        "Cuba",
        "Chipre",
        "República Checa",
        "República Democrática del Congo",
        "Dinamarca",
        "Territorio en disputa",
        "Djibouti",
        "Dominica",
        "República Dominicana",
        "Timor Occidental",
        "Ecuador",
        "Egipto",
        "El Salvador",
        "Guinea Ecuatorial",
        "Eritrea",
        "Estonia",
        "Etiopía",
        "Islas Malvinas",
        "Islas Faroe",
        "Estados Federados de Micronesia",
        "Fiji",
        "Finlandia",
        "Francia",
        "Guayana Francesa",
        "Polinesia Francesa",
        "Territorios Franceses del Sur",
        "Gabón",
        "Gambia",
        "Georgia",
        "Alemania",
        "Ghana",
        "Gibraltar",
        "Grecia",
        "Groenlandia",
        "Grenada",
        "Guadalupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haití",
        "Islas Heard y McDonald",
        "Honduras",
        "Hong Kong",
        "Hungría",
        "Islandia",
        "India",
        "Indonesia",
        "Irán",
        "Iraq",
        "Zona neutra Iraq-Arabia Saudí",
        "Irlanda",
        "Israel",
        "Italia",
        "Costa de Marfil",
        "Jamaica",
        "Japón",
        "Jordania",
        "Kazajstán",
        "Kenia",
        "Kiribati",
        "Kuwait",
        "Kirguistán",
        "Laos",
        "Letonia",
        "Líbano",
        "Lesotho",
        "Liberia",
        "Libia",
        "Liechtenstein",
        "Lituania",
        "Luxemburgo",
        "Macau",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malasia",
        "Maldivas",
        "Mali",
        "Malta",
        "Islas Marshall",
        "Martinica",
        "Mauritania",
        "Mauricio",
        "Mayotte",
        "México",
        "Moldova",
        "Mónaco",
        "Mongolia",
        "Montserrat",
        "Marruecos",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Países Bajos",
        "Antillas Holandesas",
        "Nueva Caledonia",
        "Nueva Zelanda",
        "Nicaragua",
        "Níger",
        "Nigeria",
        "Niue",
        "Isla Norfolk",
        "Corea del Norte",
        "Islas Mariana del Norte",
        "Noruega",
        "Omán",
        "Pakistán",
        "Palau",
        "Territorios Palestinos Ocupados",
        "Panamá",
        "Papúa-Nueva Guinea",
        "Paraguay",
        "Perú",
        "Filipinas",
        "Islas Pitcairn",
        "Polonia",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunión",
        "Rumanía",
        "Rusia",
        "Ruanda",
        "Santa Elena y Dependencias",
        "Saint Kitts y Nevis",
        "Santa Lucía",
        "San Pedro y Miquelón",
        "San Vicente y Granadinas",
        "Samoa",
        "San Marino",
        "Santo Tomé y Príncipe",
        "Arabia Saudí",
        "Senegal",
        "Serbia y Montenegro",
        "Seychelles",
        "Sierra Leona",
        "Singapur",
        "Eslovaquia",
        "Eslovenia",
        "Islas Salomón",
        "Somalia",
        "Sudáfrica",
        "Islas Georgia del Sur e Islas Sandwich del Sur",
        "Corea del Sur",
        "Islas Spratly",
        "Sri Lanka",
        "Sudán",
        "Surinám",
        "Islas Svalbard y Jan Mayen",
        "Swazilandia",
        "Suecia",
        "Suiza",
        "Siria",
        "Taiwán",
        "Tayikistán",
        "Tanzania",
        "Tailandia",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad y Tobago",
        "Túnez",
        "Turquía",
        "Turkmenistán",
        "Islas Turks y Caicos",
        "Tuvalu",
        "Uganda",
        "Ucrania",
        "Emiratos Árabes Unidos",
        "Reino Unido",
        "Zona neutra de las Naciones Unidas",
        "Estados Unidos",
        "Islas Menores de los Estados Unidos",
        "Uruguay",
        "Islas Vírgenes de los Estados Unidos",
        "Uzbekistán",
        "Vanuatu",
        "Vaticano",
        "Venezuela",
        "Vietnám",
        "Wallis y Futuna",
        "Sáhara Occidental",
        "Yemen",
        "Zambia",
        "Zimbabwe"};

    /** Creates a new instance of PaisesBean */
    public PaisesBean() {
    }

    public String getEspana() {
        return espana;
    }

    public void setEspana(String espana) {
        this.espana = espana;
    }

    public String[] getPaises() {
        return paises;
    }

    public void setPaises(String[] paises) {
        this.paises = paises;
    }
}
